config/routes.rb
Rails.application.routes.draw do

  
  root 'users#new'
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  
  resources :diets  
  resources :workouts
  resources :users
  resources :coaches
  resources :schedules
  resources :recipes
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
end

app/models/coach.rb
class Coach < ApplicationRecord
    belongs_to :diet
    
end

app/models/diet.rb
class Diet < ApplicationRecord
    has_many :recipes
    

end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :diet
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :coach_id
  belongs_to :user_id
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :name,  presence: true 
    validates :email, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception 
 
 def current_user 
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id] 
 end 
    helper_method :current_user 

 def authenticate_user! 
  redirect_to '/login' unless @current_user 
 end 

end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
    
    before_action :authenticate_user!
    skip_before_action :authenticate_user!, only: [:index]
   

    def new 
        @coach = Coach.new
    end

    def show
        @coach = Coach.find(params[:id])
    end

    def index
        @coaches = Coach.all
        @count = Coach.all.length
       
    end

    def create
        @coach = Coach.new(coach_params)
        if @coach.save
            redirect to coaches_path(@coach)
        else
            render :new
        end

    end

    def coach_params
        params.require(:coach).permit(:name, :bio, :diet_id, :phone, :address, :company, :url, :img)
    end

end

app/controllers/diets_controller.rb
class DietsController < ApplicationController
    
    before_action :authenticate_user!
    skip_before_action :authenticate_user!, only: [:index]
   

    def new 
        @diet = Diet.new
    end

    def index
        @diets = Diet.all
    end

    def show
        @diet = Diet.find(params[:id])
    end

    def create
        
        @diet = Diet.new(diet_params)
        if @diet.save
            redirect to diets_path(@diet)
        else
            render :new
        end
    end
    

    private

    def diet_params
        params.require(:diet).permit(:name, :description, :url, :img)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

    before_action :authenticate_user!
    skip_before_action :authenticate_user!, only: [:index]
 

    def new 
        @recipe = Recipe.new
    end

    def show
        @recipe = Recipe.find(params[:id])
    end

    def create
        
        @recipe = Recipe.new(recipe_params)
        if @recipe.save
            redirect to recipes_path(@recipe)
        else
            render :new
        end
    end
    
    def index
        @recipes = Recipe.all
    end

    private

    def recipe_params
        params.require(:recipe).permit(:name, :diet_id, :img, :url)
    end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

    before_action :authenticate_user!
    skip_before_action :authenticate_user!, only: [:index]
    
 

    def new 
        
        @schedule = Schedule.new
    end

    def create
        
        @schedule = Schedule.new(schedule_params)
        if @schedule.save
            redirect_to schedules_path(@schedule)
        else
            render :new
        end
    end

    def show
        @schedule = Schedule.find(params[:id])
    end

    def index
        
        @schedules = Schedule.all
    end

    def edit
        @schedule = Schedule.find(params[:id])
    end

    def update
        if @schedule.update
            redirect :show
        else
            render :edit
        end
    end

    private 

    def schedule_params
        params.require(:schedule).permit(:class_name, :class_type, :class_time, :class_size, :class_length, :coach_id, :user_id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        
    end

   def create
        user = User.find_by(email: params[:email])
        if !!user != false && user.authenticate(params[:password])
            session[:user_id] = user.id
            flash[:success] = "Successfully Logged In!"
            redirect_to '/diets'
        else
            flash[:warning] = "Invalid Username or Password"
            redirect_to '/login'
        end
  end

    def destroy
     session[:user_id] = nil
     flash[:success] = "Successfully Logged Out!"
     redirect_to '/login'
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new

    end

    def create
        user = User.new(
        name: params[:name],
        email: params[:email],
        password: params[:password],
        password_confirmation: params[:password_confirmation])
        if user.save
            session[:user_id] = user.id
            flash[:success]= "Successfully Created Your Account!"
            redirect_to '/coaches'
        else
            flash[:warning] = user.errors.full_messages
            redirect_to '/signup'
        end

    end



    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diets_helper.rb
module DietsHelper
end

app/views/coaches/index.html.erb
<h1>Your Coaches</h1>

<% if !!flash[:success] == true  %>
<h2><%= flash[:success] %></h2>
<% end %>
<h2><%="There are currently #{@count} coaches" %></h2>

<ul>
<% @coaches.each do |coach|  %>
<h3><%= link_to coach.name, coach %><br></h3>
<p class="coach"><%=  coach.company %><br></p>
<%=  coach.bio %><br>
<p><img src=<%= coach.img %> height='315px' width='350px'></p>





</ul>
<% end %>

app/views/coaches/new.html.erb
<h1>Add a Coach</h1>
<body>
<%= form_for @coach do |f|%>
<label> Name </label><br>
<%= f.text_field :name, :size => "45" %><br>
<label> Bio </label><br>
<%= f.text_area :bio, cols: "45", rows: "10" %><br>
<label> Add a Photo </label><br>
<%= f.text_area :img, cols: "45", rows: "10" %><br>
<label> Add Your Website </label><br>
<%= f.text_area :url, cols: "45", rows: "10" %><br>
<div class="actions"><%= f.submit "Submit your coach!", :class => "button" %>
</div>
<% end %>
</body>

app/views/coaches/show.html.erb
<h1> <%= @coach.name %></h1>

  
<div class="/root"><%= submit_tag "Back to Coaches!", :class => "button" %><br>    
     ___________________________________________________________________________________ <br>

            <%= link_to "Check out their Website", @coach.url, target: "_blank" %>

            <h3><%= @coach.bio %><br></h3>

            <h4><%= @coach.phone %><br> </h4>
            <h5><%= @coach.address %><br> </h5>
        

           <p> <img src=<%= @coach.img %> height='350px' width='350px'></p>

           
        
   
    
   

app/views/diets/index.html.erb
<h1> Available Diets </h1>
<% if !!flash[:success] == true  %>
<h2><%= flash[:success] %></h2>
<% end %>
<ul>
<% @diets.each do |diet| %>
 <h3 id="diet" > ❃ <%= link_to diet.name, diet %> ❃ </h3>
    <h3 id="diet-info"><%= diet.description  %></h3>
<% end %>

</ul>

app/views/diets/new.html.erb
<h1>Add a Diet</h1>
<body>
<%= form_for @diet do |f| %>
<label> Diet Name </label><br>
<%= f.text_field :name, :size => "45" %><br>
<label> Description </label><br>
<%= f.text_area :description, cols: "45", rows: "10" %><br>
<%= f.collection_select :coach_id, Coach.all, :id, :name %><br>
<div><%= f.submit "Submit your diet!", :class => "button" %></div>
<% end %>
</body>


<style>
h1 {
  color: cadetblue;
  font-family: impact;
  font-size: 350%;
  text-align: center;
}

body{
    color: cadetblue;
    font-family: impact;
    font-size: 200%;
  text-align: center;
  background-color: ;

}

.input-element{
font-size: 100px; // for say a select
width: 400px;
}

.button{
  background-color: gainsboro;
  color: cadetblue;
  width: 150px;
  height: 65px;
  font-size: 17px;
  font-family: impact;
  border: 3px solid powderblue;
  border-radius: 8px;

app/views/diets/show.html.erb
       <h1> <%= @diet.name %></h1>

       <h3><%= @diet.description %><br></h3>

       
       <h4> __________________________________________________________</h4><br>

        <% @diet.recipes.each do |recipe| %>

            <label> Recipe Name: </label>

            <%= link_to recipe.name, recipe.url, target: "_blank" %>

           <p> <img src=<%= recipe.img %> height='350px' width='350px'></p>

           
        
        <% end %>
    
   





   
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
  
  <header class= "header-site"> 
        
        <nav id="title">
            <%= link_to "Diets |", '/diets' %> 
            <%= link_to "Recipes |", '/recipes' %>
            <%= link_to "Coaches |", '/coaches' %> 
            <%= link_to "Signup |", '/signup' %> 
            <%= link_to "Login |", '/login' %> 
            <%= link_to "Logout", '/logout' %> 
        </nav>
        <img src="/pics/trying.png" alt="everyday wellness">
    </header> 

  <body>


<style>
  h1 {
    padding-top: 0px;
    color: #9B8884;
    font-family: bodoni;
    font-size: 200%;
    text-align: center;
    position: relative;
  }

  h2 {
    color: e0a09c;
    font-family: bodoni;
    font-size: 180%;
    text-align: left;
    margin-top: 100px;
    margin-bottom: 100px;
    margin-right: 200px;
    margin-left: 80px;
    font-style: italic;
  }

  h3 {
    color: #bda371 ;
    font-family: bodoni;
    font-size: 120 %;
    text-align: center;
  }
  h4 {
      color: ffcccc
      font-family: bodoni;
      font-size: 190% ;
      text-align: center;
     
  }

  h5 {
      color: ffcccc;
      display: inline-block;
    
  }

  #title 
  {
    text-align: center;
    
    font-size: 20px;
    
    
    
  }

  #diet {
    text-align: left;
    font-size: 125%;
  }

  #diet-info {
    font-size: 147%;
    color: #d99b97;
    font-style: italic;
  }

  header {
    margin: auto;
    position: relative;
    width: 100vw ;
    height: 450px;
    text-align: center;
    display: block;
    padding: 5px;
    
  }


  a {
    text-decoration: none;
    color: #87afb5;
  }

  body{

    font-weight: bold;
      color: darkseagreen;
      font-family: bodoni;
      font-size: 128%;
    
    background-color: #e6e0e0;
    flex-direction: row;
    align-items: center;
    justify-content: space-around;
  }
    
  nav {
    list-style-type: none ;
    margin: 3 ;
    padding: 1 ;
  }

  p {
    text-align: center;
    font-size: 100% ;
  }

div class="green text" {
  color: olivedrab;
}

.coach {
  color: #d19592;
  font-family: bodoni;
  font-size: 100%;
  display: inline-block;
}


.button{
  background-color: whitesmoke;
  color: cadetblue;
  width: 150px;
  height: 65px;
  font-size: 17px;
  font-family: bodoni MT;
  border: 3px solid powderblue;
  border-radius: 8px;



</style>
    <%= yield %>
  </body>
  </html>

app/views/recipes/index.html.erb
<h1>Your Recipes</h1>
<body>

<ul>
<% @recipes.each do |recipe|  %>

<h2> ❃ <%= recipe.diet.name %> ❃ </h2>
<h3>Click to get the recipe  ➤  <%= link_to recipe.name, recipe.url, target: :_blank %></h3>
<p><img src=<%= recipe.img %> height='580px' width='610px'></p>





</ul>
<% end %>
</body>

app/views/schedules/edit.html.erb
<h1>Update Your Schedule</h1>

<%= form_for @schedule do |s| %>
    <%= s.label "Class Name" %><br>
<%= s.text_field :class_name %><br>
<%= s.label "Class Size" %><br>
<%= s.number_field :class_size %><br>
<%= s.label "Class Type" %><br>
<%= s.text_field :class_type %><br>
<%= s.label "Class Length" %><br>
<%= s.number_field :class_length %><br>
<%= s.label "Class Date and Time" %><br>
<%= s.date_select :class_time %><br>
<%= s.label "Coach Name" %><br>
<%= s.collection_select :coach_id, Coach.all, :id, :name %><br>
<% s.submit "Update Your Schedule" %>
<% end %> 

app/views/schedules/index.html.erb
<h1>The Schedule For All Classes </h1>


<ul>
<% @schedules.each do |c|  %>
<p><%=  c.class_name %><br></p>
<p><%=  c.class_type %><br></p>
<p><%=  c.class_time %><br></p>
<p> <%=  c.class_size %></p><br>
<p> <%=  c.class_length %></p><br>

<% end %>

app/views/schedules/new.html.erb
<h1>Add A Class</h1>
<body>
<%= form_for @schedule do |s| %>
    <%= s.label "Class Name" %><br>
<%= s.text_field :class_name %><br>
<%= s.label "Class Size" %><br>
<%= s.number_field :class_size %><br>
<%= s.label "Class Type" %><br>
<%= s.text_field :class_type %><br>
<%= s.label "Class Length" %><br>
<%= s.number_field :class_length %><br>
<%= s.label "Class Date and Time" %><br>
<%= s.date_select :class_time %><br>
<%= s.label "Coach Name" %><br>
<%= s.collection_select :coach_id, Coach.all, :id, :name %><br>
<%= s.submit 'Add Your Class'%>
<% end %> 
</body>

<style>
h1 {
  color: cadetblue;
  font-family: impact;
  font-size: 280%;
  text-align: center;
}

body{
    color: cadetblue;
    font-family: impact;
    font-size: 160%;
  text-align: center;
  background-color: ;

}

app/views/schedules/show.html.erb
<h1>Your schedule</h1>


<label> Class Name: </label></br>
    <%= @schedule.class_name  %></br>
   
    <label> Class Type: </label> 

    <br><%= @schedule.class_type  %></br>

    <label> Class Time: </label> 

    <br><%= @schedule.class_time  %></br>
   
    <label> Class Size </label>
    <br><%= @schedule.class_size  %></br>
   
    <label> Class Length </label>
    <br><%= @schedule.class_length %></br>
   
    <label> Coach Id </label>
    <br><%= @schedule.coach_id  %></br>
   
    <label> User Id </label>
        <%= @schedule.user_id %>
        
    </li>
    </ul>
    <br></br>

   <%=link_to "Edit Your Schedule", edit_schedule_path(@schedule) %>

    <br><%= button_to "Delete This", @schedule, :method => :delete %></br>

app/views/users/new.html.erb
<% if !!flash[:warning] == true  %>
    <% flash[:warning].each do |message| %>
        <h3><%= message %></h3>

    <% end %>

<% end %>


<h1> Create Account</h1>
<h3>
<%=form_tag "/users", method: :post do%>
 <div>
  <%= label_tag :name%>
  <%= text_field_tag :name%>
 </div>
 <div>
  <%= label_tag :email%>
  <%= text_field_tag :email%>
 </div>
 <div>
  <%= label_tag :password%>
  <%= password_field_tag :password%>
 </div>
 <div>
  <%= label_tag :password_confirmation%>
  <%= password_field_tag :password_confirmation%>
 </div>
 
<%= submit_tag "Sign Up", class: "btn btn-default" %>
<%end%>
<h3>